# Generated by Django 4.1 on 2023-02-27 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
    ]
