# Generated by Django 4.1 on 2023-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0002_alter_user_restaurante"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurante", name="ubicacion",),
        migrations.AlterField(
            model_name="producto",
            name="unidadMedida",
            field=models.CharField(
                choices=[
                    (None, "Seleccione"),
                    ("Litros", "LITROS"),
                    ("Libras", "LIBRAS"),
                ],
                max_length=200,
            ),
        ),
    ]
