# Generated by Django 4.1 on 2023-03-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0006_plato_especial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="plato",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
    ]
