# Generated by Django 4.1 on 2023-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0007_factura_restaurante_plato_restaurante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plato",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="nombre",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
