# Generated by Django 4.1 on 2023-03-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0008_alter_plato_nombre_alter_producto_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
        migrations.AddField(
            model_name="productosfactura",
            name="restaurante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAccess.restaurante",
            ),
        ),
    ]
