# Generated by Django 4.1 on 2023-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0011_plato_imagenmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="logo",
            field=models.CharField(default="cx", max_length=200),
        ),
        migrations.AlterField(
            model_name="plato", name="imagenMenu", field=models.TextField(default="X"),
        ),
    ]
