# Generated by Django 4.1 on 2023-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0016_orden_identificator_user_isadminrest_alter_user_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden", name="estado", field=models.BooleanField(default=True),
        ),
    ]
