# Generated by Django 4.1 on 2023-09-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0002_delete_proveedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="facebook",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="horario",
            field=models.TextField(default="X"),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="instagram",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="twiter",
            field=models.CharField(default="X", max_length=200),
        ),
    ]
