# Generated by Django 4.1 on 2023-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0003_restaurante_facebook_restaurante_horario_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurante", name="horario",),
        migrations.AddField(
            model_name="restaurante",
            name="domingo",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="jueves",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="lunes",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="martes",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="miercoles",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="sabado",
            field=models.CharField(default="X", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="viernes",
            field=models.CharField(default="X", max_length=200),
        ),
    ]
