# Generated by Django 4.1 on 2023-09-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0004_remove_restaurante_horario_restaurante_domingo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurante",
            name="cantidadMesas",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="domingo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="facebook",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="instagram",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="jueves",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="lunes",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="martes",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="miercoles",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="sabado",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="twiter",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurante",
            name="viernes",
            field=models.CharField(max_length=200),
        ),
    ]
