# Generated by Django 4.1 on 2023-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0006_alter_plato_nombre_alter_producto_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagenInv",
            field=models.TextField(default="X"),
        ),
    ]
