# Generated by Django 4.1 on 2023-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0007_producto_imageninv"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="identificatorOrder",
            field=models.CharField(
                choices=[
                    (None, "Seleccione"),
                    ("Tarjeta", "TARJETA"),
                    ("Efectivo", "EFECTIVO"),
                ],
                default="x",
                max_length=200,
            ),
        ),
    ]
