# Generated by Django 4.1 on 2023-09-26 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0009_orden_pagado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="total",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
