# Generated by Django 4.1 on 2023-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0010_alter_inventario_plato_alter_inventario_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="plato", name="imagenMenu", field=models.TextField(default="x"),
        ),
    ]
