# Generated by Django 4.1 on 2023-05-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0012_restaurante_logo_alter_plato_imagenmenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesa", models.PositiveIntegerField()),
                ("horaPedido", models.DateTimeField()),
                (
                    "plato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataAccess.plato",
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataAccess.restaurante",
                    ),
                ),
            ],
        ),
    ]
