# Generated by Django 4.1 on 2023-03-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0003_remove_restaurante_ubicacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="producto", name="proveedor",),
    ]
