# Generated by Django 4.1 on 2023-03-21 04:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0004_remove_producto_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipoPago",
                    models.CharField(
                        choices=[
                            (None, "Seleccione"),
                            ("Tarjeta", "TARJETA"),
                            ("Efectivo", "EFECTIVO"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "propina",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "total",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="productosFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataAccess.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataAccess.producto",
                    ),
                ),
            ],
        ),
    ]
