# Generated by Django 4.1 on 2023-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0013_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden", name="cantidad", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="cantidadMesas",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
