# Generated by Django 4.1 on 2023-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0014_orden_cantidad_restaurante_cantidadmesas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurante", name="logo", field=models.TextField(default="X"),
        ),
    ]
