# Generated by Django 4.1 on 2023-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataAccess", "0015_alter_restaurante_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="identificator",
            field=models.TextField(default="X"),
        ),
        migrations.AddField(
            model_name="user",
            name="isAdminRest",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    (None, "Seleccione"),
                    ("Bebida", "BEBIDA"),
                    ("Principal", "PRINCIPAL"),
                    ("Postre", "POSTRE"),
                    ("Dueño", "CAJA"),
                ],
                max_length=200,
            ),
        ),
    ]
